export const bubbles = [
    {
      s: 0.6,
      x: 1124,
      y: 55,
      skill: "Git",
      desc: "",
    },
    {
      s: 0.6,
      x: 795,
      y: 226,
      skill: "Team player",
      desc: "",
    },
    {
      s: 0.6,
      x: 276,
      y: 256,
      skill: "Engineer",
      desc: "C",
    },
    {
      s: 0.5,
      x: 1150,
      y: 365,
      skill: "lol",
      desc: "",
    },
    {
      s: 0.7,
      x: 444,
      y: 193,
      skill: "Java",
      desc: "",
    },
    {
      s: 0.8,
      x: 907,
      y: 88,
      skill: "Regexp",
      desc: "",
    },
    {
      s: 0.8,
      x: 633,
      y: 320,
      skill: "Test",
      desc: "",
    },
    {
      s: 0.8,
      x: 323,
      y: 60,
      skill: "OOP PHP",
      desc: "In: bike website",
    },
    {
      s: 0.8,
      x: 129,
      y: 357,
      skill: "Next.js/Node.js",
      desc: "In: MRobosub website, personal website",
    },
    {
      s: 0.7,
      x: 1071,
      y: 233,
      skill: "test",
      desc: "",
    },
    {
      s: 1.0,
      x: 901,
      y: 365,
      skill: "React",
      desc: "",
    },
    {
      s: 1.0,
      x: 624,
      y: 111,
      skill: "C++/C",
      desc: "",
    },
    {
      s: 1.0,
      x: 75,
      y: 103,
      skill: "Javascript",
      desc: "",
    },
    {
      s: 1.0,
      x: 413,
      y: 367,
      skill: "Python",
      desc: "In: XML Corrector, ML SLURM Training",
    },
  ];