export const bubbles = [
    {
      s: 0.6,
      x: 1124,
      y: 55,
      skill: "Git",
      desc: "In: team work flow, merging and merge requests",
    },
    {
      s: 0.6,
      x: 795,
      y: 226,
      skill: "Team player",
      desc: "In: everything I do; I'm an active listener, leader, and idea pitcher",
    },
    {
      s: 0.6,
      x: 276,
      y: 256,
      skill: "DS/Algo",
      desc: "In: UMich classes and 100+ Leetcode problems",
    },
    {
      s: 0.5,
      x: 1150,
      y: 365,
      skill: "mySQL",
      desc: "In: Northrop Grumman and shopping website project",
    },
    {
      s: 0.7,
      x: 444,
      y: 193,
      skill: "Java",
      desc: "In: practice with Leetcode and interview problems in class",
    },
    {
      s: 0.8,
      x: 907,
      y: 88,
      skill: "Regexp",
      desc: "In: NG test validation retrieval, XML corrector",
    },
    {
      s: 0.8,
      x: 633,
      y: 320,
      skill: "Javascript",
      desc: "In: MRobosub website, personal website",
      },
    {
      s: 0.8,
      x: 323,
      y: 60,
      skill: "OOP PHP",
      desc: "In: shopping sorted website with public/admin mode",
    },
    {
      s: 0.8,
      x: 129,
      y: 357,
      skill: "Next/Node.js",
      desc: "In: optimizing websites I've made to refresh and load data faster",
    },
    {
      s: 0.7,
      x: 1071,
      y: 233,
      skill: "CSS",
      desc: "In: screen-dependent sizing/placing, animations of my websites",
    },
    {
      s: 1.0,
      x: 901,
      y: 365,
      skill: "React",
      desc: "In: my websites to update states, animate, and manage DOM references",
    },
    {
      s: 1.0,
      x: 624,
      y: 111,
      skill: "C++/C",
      desc: "In: BST, OOP, hash table, stack/queue, cache, pipelining projects",
    },
    {
      s: 1.0,
      x: 75,
      y: 103,
      skill: "Leadership",
      desc: "From: head lead of baking club, lead of engineering projects, becoming Eagle Scout",
    
    },
    {
      s: 1.0,
      x: 413,
      y: 367,
      skill: "Python",
      desc: "In: Northrop Grumman and MRobosub: bots, scripts, ML",
    },
  ];